name: Ember Asset Sizes

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - uses: ./.github/actions/ember-asset-size-action
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          working-directory: "ui"
